apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: example-app-1
  namespace: default
spec:
  interval: 1m0s
  path: "./kubernetes/fluxcd/repositories/example-app-1/deploy"
  prune: true
  sourceRef:
    kind: GitRepository
    name: example-app-1